<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildThisFileDirectory)=/_/Stackmaster/</PathMap>
    <StackmasterVersion>1.0.0</StackmasterVersion>
    <Version>$(StackmasterVersion)</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Authors>JStack424</Authors>
    <RepositoryUrl>https://github.com/JStack424/Stackmaster</RepositoryUrl>
  </PropertyGroup>

  <PropertyGroup>
    <StackmasterReferencePath Condition="'$(StackmasterReferencePath)' == ''">$(MSBuildThisFileDirectory)lib/local/StackmasterReferences</StackmasterReferencePath>
  </PropertyGroup>
</Project>
